<a href="https://colab.research.google.com/github/nhutHao02/ML_Lab/blob/main/Lab_4_2013252_TranNhutHao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


............# This lab is to continous dealing with **Logistic Regression**, **kNN**, and **Decision Tree** alogirthms applied to classification tasks. 

*   **Deadline: 23:59, 12/03/2023**



# Import libraries

In [2]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier

#Task 1. 
Apply **LogisticRegression** to iris dataset which aims at classifying species of iris based on sepal_length (chiều dài đài hoa), sepal_width, petal_length (chiều dài cánh hoa), petal_width. The species are '**setosa**' '**versicolor**' and '**virginica**'. 



```
from sklearn import datasets
data4 = datasets.load_iris()
```




In [3]:
data4 = datasets.load_iris()
X=np.array(data4.data)
Y=np.array(data4.target)
model = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
model = model.fit(X_train,y_train)
y_pre=model.predict(X_test)
accLogistic=metrics.accuracy_score(y_test,y_pre)
print("accuricy",metrics.accuracy_score(y_test,y_pre))
print("metrix",metrics.confusion_matrix(y_test,y_pre))





accuricy 1.0
metrix [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


#Task 2. 
Apply LogisticRegression to **MNIST** dataset (mnist.csv) which aims at classifying handwritten digits. Dataset includes 784 pixels values of images (28x28). 


```
from sklearn import datasets
# load the MNIST digits dataset
mnist = datasets.load_digits()
```



In [4]:
data4 = datasets.load_digits()
X=np.array(data4.data)
Y=np.array(data4.target)
model = KNeighborsClassifier(n_neighbors=3)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=42)
model = model.fit(X_train,y_train)

In [ ]:

y_pre=model.predict(X_test)
print("accuricy",metrics.accuracy_score(y_test,y_pre))
print("metrix",metrics.confusion_matrix(y_test,y_pre))





accuricy 1.0
metrix [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


#Task 3. 
Apply another classification algorithm named kNN, which is an instance classifcation model. 
*  3.1. Perform kNN algorithm to Iris dataset with k={1, 3, 5, …, 29}. Select the best value of k.

*   3.2. Then compare the obtained results with those using Logistic regression (based on metrics: accuracy, precision, recall, f1 measure).


In [5]:
data4 = datasets.load_iris()
X=np.array(data4.data)
Y=np.array(data4.target)
metrix={}
acc={}
recall={}
f1={}
def createModel(k):
  model = KNeighborsClassifier(n_neighbors=k)
  X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
  model = model.fit(X_train,y_train)
  y_pre=model.predict(X_test)
  metrix[k] = metrics.confusion_matrix(y_test,y_pre)
  acc[k] = metrics.accuracy_score(y_test,y_pre)
  recall[k] = metrics.recall_score(y_test,y_pre,average=None)
  f1[k] = metrics.f1_score(y_test,y_pre,average=None)

check=1

while(check<29):
    createModel(check)
    check+=2  

maxKNN=max(acc, key=acc.get)


In [ ]:
rs="KNN hiệu quả hơn" if maxKNN>accLogistic  else "accLogistis hiệu quả hơn" if maxKNN<accLogistic else   "Cả 2 hàm hiệu quả bằng nhau"
print(rs)

Cả 2 hàm hiệu quả bằng nha


#Task 4. 
Similar to Task 3, apply kNN algorithm to **mnist** dataset which included in datasets of sklearn API.
*  4.1.	Perform kNN algorithm to Iris dataset with k={1, 3, 5, …, 29}. Select the best value of k.
*  4.2.	Then compare the obtained results with those using Logistic regression (based on metrics: accuracy, precision, recall, f1 measure).


In [6]:
data4 = datasets.load_digits()
X=np.array(data4.data)
Y=np.array(data4.target)
metrix={}
acc={}
recall={}
f1={}
def createModel(k):
  model = KNeighborsClassifier(n_neighbors=k)
  X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
  model = model.fit(X_train,y_train)
  y_pre=model.predict(X_test)
  metrix[k] = metrics.confusion_matrix(y_test,y_pre)
  acc[k] = metrics.accuracy_score(y_test,y_pre)
  recall[k] = metrics.recall_score(y_test,y_pre,average=None)
  f1[k] = metrics.f1_score(y_test,y_pre,average=None)

check=1

while(check<29):
    createModel(check)
    check+=2  

maxKNN=max(acc, key=acc.get)
print(maxKNN)

5


In [ ]:
rs="KNN hiệu quả hơn" if maxKNN>accLogistic  else "accLogistis hiệu quả hơn" if maxKNN<accLogistic else   "Cả 2 hàm hiệu quả bằng nhau"
print(rs)

#Task 5. 
Compare the performance of selected classification algorithms (**Decision Treen, kNN, and Logistic Regression**) to ***spam detection***. The dataset can be accessed from the link: http://archive.ics.uci.edu/ml/datasets/Spambase 
Attribute Information:
The last column of 'spambase.csv denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail. Most of the attributes indicate whether a particular word or character was frequently occuring in the e-mail. The run-length attributes (55-57) measure the length of sequences of consecutive capital letters. For the statistical measures of each attribute, see the end of this file. Here are the definitions of the attributes: 
*  48 continuous real [0,100] attributes of type word_freq_WORD 
= percentage of words in the e-mail that match WORD, i.e. 100 * (number of times the WORD appears in the e-mail) / total number of words in e-mail. A "word" in this case is any string of alphanumeric characters bounded by non-alphanumeric characters or end-of-string. **Example**: word_freq_address: percentage of words in the e-mail that match ADDRESS.
*  6 continuous real [0,100] attributes of type char_freq_CHAR] 
= percentage of characters in the e-mail that match CHAR, i.e. 100 * (number of CHAR occurences) / total characters in e-mail
*  1 continuous real [1,...] attribute of type capital_run_length_average 
= average length of uninterrupted sequences of capital letters
*  1 continuous integer [1,...] attribute of type capital_run_length_longest 
= length of longest uninterrupted sequence of capital letters
*  1 continuous integer [1,...] attribute of type capital_run_length_total = sum of length of uninterrupted sequences of capital letters = total number of capital letters in the e-mail
*  1 nominal {0,1} class attribute of type spam = denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail. 


---


In order to compare the performance of selected algorithms, some common metrics including **accuracy, precision, recall, f1 measures** could be used.


In [ ]:
# code

#Finally,
Save a copy in your Github. Remember renaming the notebook.